### ISSUE TITLE
Todo List for search page:

### ISSUE THREAD

**Issue by LueKely** [pangilinanervin22/echoes-track-frontend#2]
Search page home:

- [ ] background image
- [x] fade in animation

Search page results:
- [x] search results loading component
- [x] search results when empty
- [x] card results component
- [ ] integration of frontend to firebase
